ARG FEDORA_MAJOR_VERSION
ARG NVIDIA_FLAVOR
ARG KERNEL

#if defined(NVIDIA)
FROM ghcr.io/ublue-os/akmods-nvidia${NVIDIA_FLAVOR}:coreos-stable-${FEDORA_MAJOR_VERSION}-${KERNEL} AS akmods-nvidia
#endif

# /* Allow build scripts to be referenced without being copied into the final image */
FROM scratch AS ctx
COPY build_files /
COPY system_files /system_files
COPY aurorafin-shared/system_files/nvidia /system_files/nvidia

# /* Base Image */
FROM ghcr.io/ublue-os/aurora-dx:stable AS base
# /* # Other possible base images include: */
# /* FROM ghcr.io/ublue-os/bazzite:testing */
# /* FROM ghcr.io/ublue-os/aurora:stable */
# /* FROM ghcr.io/ublue-os/bluefin-nvidia-open:stable */
#
# /* ... and so on, here are more base images */
# /* Universal Blue Images: https://github.com/orgs/ublue-os/packages */
# /* Fedora base image: quay.io/fedora/fedora-bootc:44 */
# /* CentOS base images: quay.io/centos-bootc/centos-bootc:stream10 */

ARG FEDORA_MAJOR_VERSION=""
ARG IMAGE_NAME="noctula"
ARG IMAGE_VENDOR="domilopment"
ARG IMAGE_TAG="latest"
ARG SHA_HEAD_SHORT=""
ARG VERSION=""

# /* ## [IM]MUTABLE /opt */
# /* # Some bootable images, like Fedora, have /opt symlinked to /var/opt, in order to */
# /* # make it mutable/writable for users. However, some packages write files to this directory, */
# /* # thus its contents might be wiped out when bootc deploys an image, making it troublesome for */
# /* # some packages. Eg, google-chrome, docker-desktop. */
# /* # */
# /* # Uncomment the following line if one desires to make /opt immutable and be able to be used */
# /* # by the package manager. */

RUN rm /opt && mkdir /opt

# /* ## MODIFICATIONS */
# /* # make modifications desired in your image and install packages by modifying the build.sh script */
# /* # the following RUN directive does all the things required to run "build.sh" as recommended. */

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/setup.sh && \
    /ctx/build.sh

# /* Include NVIDIA akmod (nvidia-lts for now) */
#if defined(NVIDIA)
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=bind,from=akmods-nvidia,src=/rpms,dst=/tmp/rpms/nvidia \
    /ctx/nvidia.sh
#endif

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/branding.sh && \
    /ctx/initramfs.sh && \
    /ctx/cleanup.sh

# /* ## LINTING */
# /* # Verify final image and contents are correct. */
RUN bootc container lint --no-truncate
